name: Warriors News Summary

on:
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 16:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Debug information
      run: |
        python --version
        pip list
    - name: Run script
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        AGENTOPS_API_KEY: ${{ secrets.AGENTOPS_API_KEY }}
        SUBSCRIBERS: ${{ secrets.SUBSCRIBERS }}
      run: |
        python -c "import sys; print(sys.path)"
        python get_warriors_news.py --email || { echo "Error occurred. Exit code: $?"; cat /home/runner/.npm/_logs/*-debug.log; exit 1; }